# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='members.Member', verbose_name='Creator')),
            ],
            options={
                'verbose_name_plural': 'Contributions',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('logo', models.ImageField(blank=True, upload_to='avatars_org', verbose_name='Logo')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('status', models.CharField(choices=[('En attente', 0), ('Accepté', 1), ('Rejeté', 2)], max_length=10, verbose_name='Status')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='members.Member', verbose_name='Creator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.Project', verbose_name='Project'),
        ),
    ]
