# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Activer'),
        ),
    ]
