# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_organization_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiver'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to='avatars_org', verbose_name='Logo'),
        ),
    ]
