# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160628_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to='avatars_projects', verbose_name='Logo'),
        ),
    ]
