# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160628_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/avatars_org', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/avatars_projects', verbose_name='Logo'),
        ),
    ]
